local OreTypes = {
	Stone = {
		name     = "Stone",
		color    = BrickColor.new("Medium stone grey"),
		material = Enum.Material.Granite,
		hp       = 2,
		coins    = 1,
	},
	Iron = {
		name     = "Iron",
		color    = BrickColor.new("Fossil"),
		material = Enum.Material.SmoothPlastic,
		hp       = 3,
		coins    = 3,
	},
	Gold = {
		name     = "Gold",
		color    = BrickColor.new("Bright yellow"),
		material = Enum.Material.Neon,
		hp       = 5,
		coins    = 8,
	},
	Diamond = {
		name     = "Diamond",
		color    = BrickColor.new("Cyan"),
		material = Enum.Material.Neon,
		hp       = 8,
		coins    = 20,
	},
}

return OreTypes